title: "Soumik Ghosh"
email: "soumik.ghosh@fulbrightmail.org"

logo: "assets/IMG_4829.png"
description: "Atmospheric & Climate Researcher | Extreme Weather & Climate Risk Analysis | Climate Modeling & Change"
search: true
show_downloads: true
# theme: jekyll-theme-minimal
# theme: jekyll-theme-dinky
theme: jekyll-theme-cayman




plugins:
  - jekyll-seo-tag
  - jekyll-sitemap


<footer>
  <p>© 2025 Soumik Ghosh </p>
</footer>

