title: "Soumik Ghosh"
email: "soumik.ghosh@fulbrightmail.org"
logo: "assets/IMG_4829.png"
description: "Atmospheric & Climate Researcher | Extreme Weather & Climate Risk Analysis | Climate Modeling & Change"
theme: "jekyll-theme-minimal"
