# theme: jekyll-theme-minimal
# theme: jekyll-theme-cayman

# Theme Selection
theme: jekyll-theme-minimal

# Website Title and Email
title: "Soumik Ghosh"

# Logo & Description
logo: "assets/IMG_4829.png"
# description: "Atmospheric & Climate Researcher | Extreme Weather & Climate Risk Analysis | Climate Modeling & Change"
# description: "<strong style='color:#3498DB;'>Atmospheric & Climate Researcher | Extreme Weather & Climate Risk Analysis | Climate Modeling & Change</strong>"
description: |
  <div style="text-align: center; color: #3498DB; font-weight: bold;">
    Atmospheric & Climate Researcher <br><br>
    Extreme Weather & Climate Risk Analysis <br><br>
    Climate Modeling & Change
  </div>

search: true
# show_downloads: true  # Enable downloads

# SEO and Sitemap Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap


# Footer Information
copyright: "© 2025 Soumik Ghosh. All rights reserved."


