title: Soumik Ghosh
email: soumik.ghosh@fulbrightmail.org
# Social Links
social:
  linkedin: "https://www.linkedin.com/in/soumik-ghosh-97004277/?originalSubdomain=ca"
  google_scholar: "https://scholar.google.co.in/citations?user=ds5ggVoAAAAJ&hl=en"
  researchgate: "https://www.researchgate.net/profile/Soumik-Ghosh-2"
  orcid: "https://github.com/user-attachments/assets/b5199a6e-10e9-40a0-8f41-7e6c3071f61b"

# logo: assets/IMG_4829.png
description: Atmospheric & Climate Researcher | Extreme Weather & Climate Risk Analysis | Climate Modeling-Change & Policy
search: true
# show_downloads: true
theme: jekyll-theme-minimal

