# Theme Selection
theme: jekyll-theme-minimal

# Website Title and Email
title: "Soumik Ghosh"

# Remove this parameter if you don't want an image in the navbar
avatar: "assets/IMG_4829.png"

# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: true

# Logo & Description
# logo: "assets/IMG_4829.png"
description: "<strong style='color:#000000;'>Atmospheric & Climate Researcher | Extreme Weather & Climate Risk Analysis | Climate Modeling & Change</strong>"

search: true
# show_downloads: true  # Enable downloads

# SEO and Sitemap Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap




