title: "Soumik Ghosh"
email: "soumik.ghosh@fulbrightmail.org"

logo: "assets/IMG_4829.png"
description: "Atmospheric & Climate Researcher | Extreme Weather & Climate Risk Analysis | Climate Modeling & Change"
search: true
show_downloads: true
theme: "jekyll-theme-minimal"

# Additional settings for better functionality
author: "Soumik Ghosh"
baseurl: ""  # Leave empty if deploying to the root domain
url: "https://your-github-username.github.io"  # Replace with your actual GitHub Pages URL
github_username: "your-github-username"  # Replace with your GitHub username

# Navigation links (optional)
nav:
  - title: "Home"
    url: "/"
  - title: "Publications"
    url: "/publications"
  - title: "Projects"
    url: "/projects"
  - title: "Contact"
    url: "/contact"

# Plugins (optional)
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
