# theme: jekyll-theme-minimal
# theme: jekyll-theme-cayman

title: "Soumik Ghosh"
email: "soumik.ghosh@fulbrightmail.org"

theme: jekyll-theme-minimal
logo: "assets/IMG_4829.png"
description: "Atmospheric & Climate Researcher | Extreme Weather & Climate Risk Analysis | Climate Modeling & Change"
search: true
show_downloads: true

# SEO and Sitemap
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Social Media Links
social_links:
  linkedin: "https://www.linkedin.com/in/YOUR-LINKEDIN/"
  scholar: "https://scholar.google.com/citations?user=YOUR-SCHOLAR-ID"
  github: "https://github.com/YOUR-GITHUB"
  twitter: "https://twitter.com/YOUR-TWITTER"
  researchgate: "https://www.researchgate.net/profile/YOUR-PROFILE"


