title: Soumik Ghosh
logo: https://github.com/SoumikGhosh1/SoumikGhosh1/blob/18d94a1b27800f1b40f684811adf1b49377da797/assets/IMG_4829.png
description: Atmospheric & Climate Researcher | Extreme Weather & Climate Risk Analysis | Climate Modeling-Change & Policy
show_downloads: true
theme: jekyll-theme-minimal
