title: Soumik Ghosh
logo: https://github.com/SoumikGhosh1/SoumikGhosh1/blob/main/assets/IMG_4829.JPG?raw=true
description: Atmospheric & Climate Researcher | Extreme Weather & Climate Risk Analysis | Climate Modeling-Change & Policy
show_downloads: true
theme: jekyll-theme-minimal
